resolver: lts-20.18
packages:
- Cabal/
- cabal-install/
- cabal-testsuite/
nix:
  packages:
  - autoconf
  - automake
  - haskellPackages.happy
  - haskellPackages.alex
  - zlib
  - zlib.out

allow-newer: true
